"""add_modules_to_user_timetables

Revision ID: c75f61e2cbf8
Revises: 52e30341c73c
Create Date: 2026-06-26 15:27:44.752065

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c75f61e2cbf8'
down_revision: str | Sequence[str] | None = '52e30341c73c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_timetables', sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_timetables', 'modules')
    # ### end Alembic commands ###
